"""Public API of leadradar-ai (SPEC §1.4.1) — the only module core may import.

Config helpers (expand_question, …), presets and evals are added here as they are implemented.
"""

from leadradar_ai.contracts import (
    AnalysisDocument,
    AnalysisInput,
    ChunkIn,
    CollectRequest,
    CompanyProfile,
    Contribution,
    Criterion,
    FitResult,
    ICPConfig,
    LeadScore,
    LLMCallRecord,
    ProgressEvent,
    QuestionConfig,
    Reason,
    RejectedEvidence,
    RuleConfig,
    RunStats,
    ScoreChange,
    ScoringProfile,
    ServiceBundle,
    Snippet,
    StepError,
    StoredSignal,
    VerifiedSignal,
)
from leadradar_ai.errors import (
    AnalysisPaused,
    ExtractionFailed,
    LeadRadarAIError,
    LLMBadRequest,
    LLMInputTooLarge,
    LLMUnavailable,
    QuotaExhausted,
)
from leadradar_ai.llm import GeminiClient, LLMClient, LLMRequest, LLMResult
from leadradar_ai.pipeline import (
    AnalysisDeps,
    AnalysisOutput,
    build_analysis_graph,
    run_analysis,
    thread_config,
)
from leadradar_ai.ports import AnalysisStore, Collector, Embedder, LLMCache, ProgressSink, UsageSink
from leadradar_ai.retrieval import FastEmbedder
from leadradar_ai.scoring import evaluate_rules, fit_score, lead_sort_key, score_company
from leadradar_ai.settings import AISettings, LLMSettings

__all__ = [
    "AISettings",
    "AnalysisDeps",
    "AnalysisDocument",
    "AnalysisInput",
    "AnalysisOutput",
    "AnalysisPaused",
    "AnalysisStore",
    "ChunkIn",
    "CollectRequest",
    "Collector",
    "CompanyProfile",
    "Contribution",
    "Criterion",
    "Embedder",
    "ExtractionFailed",
    "FastEmbedder",
    "FitResult",
    "GeminiClient",
    "ICPConfig",
    "LLMBadRequest",
    "LLMCache",
    "LLMCallRecord",
    "LLMClient",
    "LLMInputTooLarge",
    "LLMRequest",
    "LLMResult",
    "LLMSettings",
    "LLMUnavailable",
    "LeadRadarAIError",
    "LeadScore",
    "ProgressEvent",
    "ProgressSink",
    "QuestionConfig",
    "QuotaExhausted",
    "Reason",
    "RejectedEvidence",
    "RuleConfig",
    "RunStats",
    "ScoreChange",
    "ScoringProfile",
    "ServiceBundle",
    "Snippet",
    "StepError",
    "StoredSignal",
    "UsageSink",
    "VerifiedSignal",
    "build_analysis_graph",
    "evaluate_rules",
    "fit_score",
    "lead_sort_key",
    "run_analysis",
    "score_company",
    "thread_config",
]
