"""Worker side of runs: config errors finish the run, cancellation stops the graph, mode=full, live SSE names
equal replay names, embedded vs queued dispatch, outreach generated by a worker task.

Fixtures are shared with test_ai_integration (imported below; pytest injects them by parameter name).
"""
# ruff: noqa: F811

import asyncio
import json
from uuid import UUID, uuid4

import leadradar_parser as parser
import pytest
from leadradar_ai.testing import FakeLLM
from leadradar_core.db.session import async_session_factory, engine
from leadradar_core.modules.runs.models import AnalysisRun, RunEvent
from leadradar_core.settings import AppSettings, settings
from leadradar_core.worker import enqueue, outreach, tasks
from leadradar_core.worker.deps import worker_context
from sqlalchemy import select, update
from test_ai_integration import (  # noqa: F401 (fixtures)
    client,
    create_run,
    fake_parser,
    fake_worker,
    fresh_engine,
    headers,
    org_id,
    seed,
)
from test_runs_sse import parse_sse


async def run_row(run_id: UUID) -> AnalysisRun:
    async with async_session_factory() as session:
        return await session.get(AnalysisRun, run_id)


async def run_events(run_id: UUID) -> list[tuple[str, str]]:
    async with async_session_factory() as session:
        rows = await session.execute(
            select(RunEvent.stage, RunEvent.status).where(RunEvent.run_id == run_id).order_by(RunEvent.id)
        )
        return [(r.stage, r.status) for r in rows]


class FakeRedis:
    def __init__(self) -> None:
        self.messages: list[dict] = []

    async def publish(self, channel: str, message: str) -> None:
        self.messages.append({"channel": channel, **json.loads(message)})


# --- item 1: the API only enqueues --------------------------------------------------------------


def test_embedded_worker_is_off_by_default() -> None:
    assert AppSettings.model_fields["EMBEDDED_WORKER"].default is False


class RecordingTask:
    def __init__(self) -> None:
        self.kiq_calls: list[tuple] = []
        self.direct_calls: list[tuple] = []

    async def kiq(self, *args) -> None:
        self.kiq_calls.append(args)

    async def __call__(self, *args) -> str:
        self.direct_calls.append(args)
        return "done"


@pytest.mark.parametrize("embedded", [False, True])
async def test_enqueue_goes_to_the_queue_unless_embedded(monkeypatch, embedded: bool) -> None:
    task = RecordingTask()
    monkeypatch.setattr(tasks, "analyze_company", task)
    monkeypatch.setattr(settings, "ENV", "dev")
    monkeypatch.setattr(settings, "EMBEDDED_WORKER", embedded)
    run_id, company_id = uuid4(), uuid4()
    assert await enqueue.enqueue_analysis(run_id, [company_id], [], "full") == 1
    await asyncio.sleep(0)  # let the embedded background task run
    expected = [(str(run_id), str(company_id), [], "full")]
    assert (task.direct_calls, task.kiq_calls) == ((expected, []) if embedded else ([], expected))


# --- item 2: configuration errors fail the company and finish the run ----------------------------


async def test_config_error_fails_company_and_finishes_run(org_id, fake_worker, fake_parser, monkeypatch):
    service_id, company_id = await seed(org_id)
    run_id = await create_run(org_id, [company_id], [service_id])

    async def broken_bundles(*args, **kwargs):
        raise ValueError("invalid scoring profile")

    monkeypatch.setattr(tasks, "load_bundles", broken_bundles)
    assert await tasks.analyze_company(str(run_id), str(company_id), [str(service_id)]) == "failed"
    run = await run_row(run_id)
    assert (run.status, run.progress["failed"], run.finished_at is not None) == ("failed", 1, True)
    assert "invalid scoring profile" in run.error
    events = await run_events(run_id)
    assert ("company", "failed") in events and events[-1] == ("run", "failed")
    assert fake_worker.calls == []


async def test_missing_company_or_no_services_finish_the_run(org_id, fake_worker, fake_parser):
    service_id, company_id = await seed(org_id)
    missing = uuid4()
    run_id = await create_run(org_id, [company_id, missing], [uuid4()])  # unknown service: no bundles
    assert await tasks.analyze_company(str(run_id), str(company_id), [str(uuid4())]) == "failed"
    assert await tasks.analyze_company(str(run_id), str(missing), [str(service_id)]) == "failed"
    run = await run_row(run_id)
    assert (run.status, run.progress["failed"]) == ("failed", 2)
    assert "No active services" in run.error


async def test_worker_moves_queued_run_to_running(org_id, fake_worker, fake_parser):
    service_id, company_id = await seed(org_id)
    other = (await seed(org_id))[1]
    run_id = await create_run(org_id, [company_id, other], [service_id])
    assert (await run_row(run_id)).status == "queued"
    await tasks.analyze_company(str(run_id), str(company_id), [str(service_id)])
    run = await run_row(run_id)
    assert run.status == "running" and run.started_at is not None


# --- item 5: cancellation stops a running analysis -----------------------------------------------


async def cancel(run_id: UUID) -> None:
    async with async_session_factory() as session, session.begin():
        await session.execute(update(AnalysisRun).where(AnalysisRun.id == run_id).values(status="cancelled"))


async def test_cancel_is_seen_between_stages(org_id, fake_worker, fake_parser, monkeypatch):
    """The run is cancelled while collecting; the next stage event stops the graph (no LLM call)."""
    service_id, company_id = await seed(org_id)
    run_id = await create_run(org_id, [company_id], [service_id])
    monkeypatch.setattr(tasks, "CANCEL_POLL_S", 60)  # only the stage check can stop it in time

    async def collect_then_cancel(company, plan, *, http=None):
        await cancel(run_id)
        return parser.CollectResult(documents=fake_parser, errors=[], stats={}, duration_ms=1)

    monkeypatch.setattr(parser, "collect", collect_then_cancel)
    result = await asyncio.wait_for(
        tasks.analyze_company(str(run_id), str(company_id), [str(service_id)]), timeout=30
    )
    assert result == "cancelled"
    assert fake_worker.calls == []
    run = await run_row(run_id)
    assert run.status == "cancelled" and run.progress["done"] == 0
    events = await run_events(run_id)
    assert events[-1] == ("company", "cancelled")
    assert ("extracting", "started") not in events and ("collecting", "done") not in events


async def test_cancel_interrupts_a_long_stage(org_id, fake_worker, fake_parser, monkeypatch):
    """A stage that hangs (slow collection) is interrupted by the periodic status check."""
    service_id, company_id = await seed(org_id)
    run_id = await create_run(org_id, [company_id], [service_id])
    monkeypatch.setattr(tasks, "CANCEL_POLL_S", 0.1)
    release = asyncio.Event()
    started = asyncio.Event()

    async def slow_collect(company, plan, *, http=None):
        started.set()
        await release.wait()
        return parser.CollectResult(documents=[], errors=[], stats={}, duration_ms=1)

    monkeypatch.setattr(parser, "collect", slow_collect)
    job = asyncio.create_task(tasks.analyze_company(str(run_id), str(company_id), [str(service_id)]))
    await asyncio.wait_for(started.wait(), timeout=30)
    await cancel(run_id)
    try:
        assert await asyncio.wait_for(job, timeout=10) == "cancelled"
    finally:
        release.set()
    assert fake_worker.calls == []
    assert (await run_row(run_id)).status == "cancelled"


async def test_cancelled_run_is_not_started(org_id, fake_worker, fake_parser):
    service_id, company_id = await seed(org_id)
    run_id = await create_run(org_id, [company_id], [service_id])
    await cancel(run_id)
    assert await tasks.analyze_company(str(run_id), str(company_id), [str(service_id)]) == "skipped"
    assert fake_worker.calls == []


# --- item 6: mode=full re-extracts --------------------------------------------------------------


async def test_full_mode_ignores_the_fingerprint(org_id, fake_worker, fake_parser):
    service_id, company_id = await seed(org_id)
    first = await create_run(org_id, [company_id], [service_id])
    assert await tasks.analyze_company(str(first), str(company_id), [str(service_id)]) == "done"
    assert len(fake_worker.calls) == 1
    incremental = await create_run(org_id, [company_id], [service_id])
    await tasks.analyze_company(str(incremental), str(company_id), [str(service_id)], "incremental")
    assert len(fake_worker.calls) == 1  # nothing new: skipped by fingerprint
    full = await create_run(org_id, [company_id], [service_id])
    assert await tasks.analyze_company(str(full), str(company_id), [str(service_id)], "full") == "done"
    assert len(fake_worker.calls) == 2


# --- item 3: live and replay use the same names and data ------------------------------------------


async def test_live_events_match_the_replay(org_id, fake_worker, fake_parser, client, monkeypatch):
    redis = FakeRedis()
    monkeypatch.setattr(worker_context, "redis", redis)
    service_id, company_id = await seed(org_id)
    run_id = await create_run(org_id, [company_id], [service_id])
    await tasks.analyze_company(str(run_id), str(company_id), [str(service_id)])
    await engine.dispose()

    live = [{"id": m["id"], "event": m["event"], "data": m["data"]} for m in redis.messages]
    assert {m["channel"] for m in redis.messages} == {f"run:{run_id}"}
    replay = parse_sse(client.get(f"/api/v1/runs/{run_id}/events", headers=headers(org_id)).text)
    assert replay == live
    names = [e["event"] for e in live]
    assert set(names) == {"company.stage", "company.done", "run.progress", "run.finished"}
    assert names[-1] == "run.finished" and live[-1]["data"]["status"] == "succeeded"
    stage = next(e for e in live if e["event"] == "company.stage")
    assert {"company_id", "service_id", "stage", "status", "message"} <= set(stage["data"])
    done = next(e for e in live if e["event"] == "company.done")
    assert done["data"]["company_id"] == str(company_id) and done["data"]["scores"]


# --- item 8: outreach is generated by the worker -------------------------------------------------

DRAFT = {
    "channel": "email",
    "subject": "Agentic AI at Acme",
    "body": "Hello, we saw that Acme uses agentic AI for RFQs.",
    "referenced_signals": [],
    "referenced_quotes": [],
    "hook": "agentic AI",
    "call_to_action": "15 minutes next week?",
    "language": "en",
}


async def test_outreach_is_enqueued_and_generated_by_the_worker(org_id, fake_worker, client, monkeypatch):
    service_id, company_id = await seed(org_id)
    await engine.dispose()
    enqueued: list[UUID] = []

    async def fake_enqueue(job_id):
        enqueued.append(job_id)
        return True

    from leadradar_core.modules.outreach import service as outreach_service

    monkeypatch.setattr(outreach_service, "enqueue_outreach", fake_enqueue)
    h = headers(org_id)
    res = client.post(f"/api/v1/leads/{company_id}/outreach", json={"tone": "direct"}, headers=h)
    assert res.status_code == 202, res.text
    job = res.json()
    assert job["status"] == "queued" and job["draft"] is None and job["service_id"] == str(service_id)
    assert enqueued == [UUID(job["id"])]
    assert fake_worker.calls == []  # no LLM inside the request

    llm = FakeLLM([DRAFT])
    monkeypatch.setattr(worker_context, "llm", llm)
    await engine.dispose()  # pooled connections of the TestClient loop
    assert await outreach.generate_outreach(job["id"]) == "succeeded"
    assert llm.calls_for("outreach")
    assert await outreach.generate_outreach(job["id"]) == "skipped"  # a job runs once
    await engine.dispose()

    got = client.get(f"/api/v1/leads/{company_id}/outreach/{job['id']}", headers=h)
    assert got.status_code == 200
    body = got.json()
    assert body["status"] == "succeeded" and body["finished_at"]
    assert body["draft"]["subject"] == DRAFT["subject"] and body["draft"]["body"] == DRAFT["body"]

    assert client.get(f"/api/v1/leads/{company_id}/outreach/{uuid4()}", headers=h).status_code == 404
    assert client.get(f"/api/v1/leads/{uuid4()}/outreach/{job['id']}", headers=h).status_code == 404
    assert client.post(f"/api/v1/leads/{uuid4()}/outreach", json={}, headers=h).status_code == 404
