"""outreach_job: outreach drafts are generated by the worker; the API enqueues and polls them

Revision ID: 2026_09_26_outreach_job
Revises: 2026_09_26_run_status_queued
Create Date: 2026-09-26 10:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "2026_09_26_outreach_job"
down_revision: str | None = "2026_09_26_run_status_queued"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "outreach_job",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column(
            "company_id", sa.Uuid(), sa.ForeignKey("core.company.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "service_id", sa.Uuid(), sa.ForeignKey("core.service.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("status", sa.String(32), server_default="queued", nullable=False),
        sa.Column("request", JSONB(), server_default="{}", nullable=False),
        sa.Column("result", JSONB(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="core",
    )
    op.create_index(
        "idx_outreach_job_company_created", "outreach_job", ["company_id", "created_at"], schema="core"
    )


def downgrade() -> None:
    op.drop_index("idx_outreach_job_company_created", table_name="outreach_job", schema="core")
    op.drop_table("outreach_job", schema="core")
